-- MySQL Script generated by MySQL Workbench
-- Thu Apr  5 15:03:28 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Host`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Host` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Host` (
  `spotifyID` VARCHAR(45) NOT NULL,
  `displayName` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `link` VARCHAR(45) NULL,
  `profileImage` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `spotifyURI` VARCHAR(45) NOT NULL,
  `refreshToken` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`spotifyID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Guest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Guest` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Guest` (
  `idGuestTable` INT NOT NULL AUTO_INCREMENT,
  `macAddress` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGuestTable`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`playlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`playlist` ;

CREATE TABLE IF NOT EXISTS `mydb`.`playlist` (
  `playlistID` VARCHAR(45) NOT NULL,
  `spotifyID` VARCHAR(45) NOT NULL,
  `description` VARCHAR(280) NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`playlistID`, `spotifyID`),
  INDEX `fk_playlistTable_HostTable_idx` (`spotifyID` ASC),
  CONSTRAINT `fk_playlistTable_HostTable`
    FOREIGN KEY (`spotifyID`)
    REFERENCES `mydb`.`Host` (`spotifyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`party`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`party` ;

CREATE TABLE IF NOT EXISTS `mydb`.`party` (
  `partyID` INT NOT NULL AUTO_INCREMENT,
  `playlist_playlistID` VARCHAR(45) NOT NULL,
  `danceabily` INT NULL,
  `speechiness` INT NULL,
  `energy` INT NULL,
  `tempo` INT NULL,
  `valiance` INT NULL,
  PRIMARY KEY (`partyID`, `playlist_playlistID`),
  INDEX `fk_party_playlist1_idx` (`playlist_playlistID` ASC),
  CONSTRAINT `fk_party_playlist1`
    FOREIGN KEY (`playlist_playlistID`)
    REFERENCES `mydb`.`playlist` (`playlistID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`vote` ;

CREATE TABLE IF NOT EXISTS `mydb`.`vote` (
  `Guest_idGuestTable` INT NOT NULL,
  `party_partyID` INT NOT NULL,
  `danceabily` INT NULL,
  `speechiness` INT NULL,
  `energy` INT NULL,
  `tempo` INT NULL,
  `valiance` INT NULL,
  PRIMARY KEY (`Guest_idGuestTable`, `party_partyID`),
  INDEX `fk_vote_party1_idx` (`party_partyID` ASC),
  CONSTRAINT `fk_vote_Guest1`
    FOREIGN KEY (`Guest_idGuestTable`)
    REFERENCES `mydb`.`Guest` (`idGuestTable`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vote_party1`
    FOREIGN KEY (`party_partyID`)
    REFERENCES `mydb`.`party` (`partyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
